### ISSUE TITLE
Allow different boards to be saved and accessed from within Kanbanist

### ISSUE THREAD

**Issue by nthwhite** [mwakerman/kanbanist#17]
Currently each board (comprising a particular set of filter settings) has to be saved locally as a browser bookmark (a feature that incidentally no longer works: see #16). It would be much easier if boards could be configured and saved within kanbanist itself.

It kind of looks like this is already a planned feature given that there is a button labeled 'Board' sitting above the filter toolbar which currently doesn't seem to do anything useful. Is this this space where additional buttons would appear enabling access to different, user configured boards?

**Comment by mwakerman** [comment]
Hi, thanks for writing up your request. The problem with "saved boards" is that Kanbanist is a static, serverless site that talks directly to Todoist and there isn't anywhere to save a board that could be loaded later on. It could be saved locally in the one web browser but I fear that would be confusing for people without a technical understanding. Hence why "bookmarked boards" was the solution I chose.

**Comment by mwakerman** [comment]
Issue #16 now closed and bookmarks are once again working.

**Comment by nthwhite** [comment]
Understood. Thanks for explaining that. I'll continue using bookmarks now that you've fixed the issue. :-)

**Comment by mwakerman** [comment]
No worries!
