### ISSUE TITLE
Add dynamic due date filter for "Today"

### ISSUE THREAD

**Issue by fschirinzi** [mwakerman/kanbanist#21]
When defining a due date filter, a unix formatted string is added to the url.
When 'today' is choosen as due date and the view is added as bookmark and reopend the next day, the due date filter is not updated to the today's date.

Maybe changing the added filter to the url as word and then convert into a unix formatted timestamp for making the request would be better?

**Comment by mwakerman** [comment]
Hi @fschirinzi - @XuanLi-Leong-UIUC has just added this feature for you. There is now a "Today" option for the dynamic date filters at the top of the filter pane.
