### ISSUE TITLE
Include hierarchy in Projects Filter

### ISSUE THREAD

**Issue by alexanderzimmerman** [mwakerman/kanbanist#28]
My workflow would greatly benefit from being able to enable/disable Project Filters relative to the hierarchy in Todoist; e.g. checking or unchecking a parent project would automatically check or uncheck child projects.

P.S: Thanks for creating this tool. I'm very interested in this project, as it meets a specific need I've had for a long time.

**Comment by mwakerman** [comment]
Hi @alexanderzimmerman, thanks for the suggestion. I think this is a great idea. I'm in the process of a pretty major re-write of the drag-and-drop (which has been buggy everywhere and non-usable in Safari for a while) but will take a look at this after that.

Thanks!

**Comment by cosnomi** [comment]
I'm working on it.
