### ISSUE TITLE
Add support for Toggl button

### ISSUE THREAD

**Issue by ArkadyBuryakov** [mwakerman/kanbanist#33]
I appreciate your work much! 

I think this feature would help users to be more productive during their work.

There is an integration between toggl and todoist that allows to track time in toggle from todoist web applictation: https://toggl.com/todoist-time-tracking/

It would be convenient to have a support for toggl button in kanbanist, so user could avoid double checking tasks in kanbanist and todoist during working prosess

**Comment by ArkadyBuryakov** [comment]
I found Toggl documentation about adding new toggl button integrations: https://github.com/toggl/toggl-button/wiki/Adding-new-integrations

**Comment by cosnomi** [comment]
I am interested in this feature. I will try to work on this, though it looks pretty hard for me. Don't expect too much.

**Comment by cosnomi** [comment]
@mwakerman Can I ask your view on this integration? It does not affect this repository itself, so maybe I don't have to ask you a review for this, but just in case.

**Comment by mwakerman** [comment]
I'm happy for someone to add this integration if there is a way to prevent it from loading or being visible for users that do not use toggle.

**Comment by cosnomi** [comment]
@mwakerman Thanks. Because the Toggl button just adds an HTML tag to the web page on the client side, it does not need Kanbanist's change nor affects users who do not use Toggl.
Now I will remove WIP from the PR and await Toggl button's review.

**Comment by cosnomi** [comment]
https://github.com/toggl/toggl-button/pull/1318 has been merged, and the latest release of toggl-button ( `1.25.0` ) includes this integration. You can now start or stop the toggl timer from a kanbanist panel!  

@mwakerman 
Thank you for your cooperation. This issue can be now closed.
