### ISSUE TITLE
Bug: When creating task in Kanbanist, labels aren't recognize

### ISSUE THREAD

**Issue by JohnWebmaster** [mwakerman/kanbanist#44]
Steps to replicate:

1. I create a task called "Test Task today #work" in a column called "Ready 2".
2. A task is created in the backlog column called "Test Task @ready_2".

**Comment by mwakerman** [comment]
Hi @JohnWebmaster - thanks for reporting this issue. Unfortunately I'm unable to repro using the same parameters that you've provided which makes it difficult to fix. See: https://imgur.com/a/KHecDZl

**Comment by mwakerman** [comment]
Closing this issue as unable to reproduce issue.
