### ISSUE TITLE
Update to Todoist API v8

### ISSUE THREAD

**Issue by resort-diaper** [mwakerman/kanbanist#47]
As of August 30th 2019 v7 of the Todoist API has been removed as per [https://developer.todoist.com/sync/v7/](https://developer.todoist.com/sync/v7/).

As this date has now passed [kanban.ist](kanban.ist) will not work until the API used is updated to v8.

**Comment by mwakerman** [comment]
Thanks for reporting. I believe I've been able to do this. Let me know if you have any issues.
