### ISSUE TITLE
When Filtering for Today, Backlogged Tasks Don't Appear

### ISSUE THREAD

**Issue by Nornwen** [mwakerman/kanbanist#49]
If I have backlog open while no filters on, I do see tasks in backlog... however once I filter for today no tasks show under backlog, despite me knowing there are 20 or so that should.

To deal with this I created a label for unsorted instead, separate from the actual backlog. If I label all my unsorted tasks for today under that they show up with the today filter...

However I experimented and dragged one of those tasks from unsorted to the actual backlog... the task stayed in the backlog column for a few seconds, then disappeared. The task is still in todoist, still labeled for today, however it doesn't appear in kanbanist with the just the today filter.

**Comment by baba43** [comment]
You are having the same issue as described here, right?

https://github.com/mwakerman/kanbanist/issues/48

**Comment by Nornwen** [comment]
Yes it is, thanks!

**Comment by mwakerman** [comment]
Duplicate of #48 (now closed).
