### ISSUE TITLE
I love Kanbanist! :-) How do I show completed tasks? I manually added them, but made the mistake of marking them all as done and then they disappeared from the list! :-)

### ISSUE THREAD

**Issue by rymeld** [mwakerman/kanbanist#51]

**Comment by rymeld** [comment]
![2019-09-25_082120](https://user-images.githubusercontent.com/1009654/65578328-80fcef00-df6d-11e9-9582-80c2830a2826.jpg)

**Comment by mwakerman** [comment]
Hi @rymeld, in Todoist you can go to a project and view completed tasks. From there you can un-complete tasks. Unfortunately this isn't possible in Kanban.ist
