### ISSUE TITLE
Display time

### ISSUE THREAD

**Issue by HaGeSo** [mwakerman/kanbanist#57]
Is it possible to display also the time if a task has a specific time, for example "today 9:00"

**Comment by dbarnett** [comment]
Interesting... JS utilities don't make any distinction between
  2019-01-01 00:00
and
  2019-01-01
JS developers don't have any helpful solutions and just suggest you overload "00:00" to mean "no time": https://stackoverflow.com/questions/21171794/check-if-a-moment-contains-a-time.
