### ISSUE TITLE
Todoist items with due dates do not show up at all in Kanbanist 

### ISSUE THREAD

**Issue by rm2101** [mwakerman/kanbanist#58]
When I log into Kanbanist, it only shows the backlog with all the items which do not have a due date. Any item with a due date does not show up anywhere in Kanbanist. 

Does anyone else have this problem? Can someone please help? Thank you!

**Comment by dbarnett** [comment]
I definitely see items with and without due dates in my Backlog section. Is it possible you have some filters selected like a "Due Date" filter? It would show up in the URL like `&filter=SOMETHING`.

**Comment by mwakerman** [comment]
Seems like a duplicate of #48 (now fixed).
