### ISSUE TITLE
Multiple Boards using different filters

### ISSUE THREAD

**Issue by JoPe72** [mwakerman/kanbanist#59]
I am not sure if this is an issue... or a feature request... or a support request. I am sorry if I ask this in the wrong forum

Is it possible to have more than one Kanbanist board pointing to my todoist account? Eg One for personal tasks, one for customer tasks, one for family etc?

**Comment by mwakerman** [comment]
Hi @JoPe72 - Kanban.ist boards can be setup using filters. Each filter you create can then be bookmarked in your browser to be 'saved'.
