### ISSUE TITLE
Rewrite drag and drop integration

### ISSUE THREAD

**Issue by dbarnett** [mwakerman/kanbanist#60]
The current drag and drop integration based on react-dnd suffers from various longstanding issues like major visual quirks and offsets while dragging (#9) and lack of mobile screen support (#22). It should be updated to something more stable and maintainable.

http://github.com/rcdexta/react-trello looks like a great drop-in solution to implement all of the UI and interactions for draggable boards and items.

**Comment by mwakerman** [comment]
I've begun this work. It's fairly significant as it requires an update to react/react-dom which requires updates to react-redux and routers and all sorts of other fun stuff. Most significantly, BlueprintJS (the UI framework) underwent significant changes in later versions which I'm working through now (basically every component needs to be checked/tweaked for small API changes). Once this upgrade is done, I'll look to move to `react-beautiful-dnd`, which I've used before and I don't expect to be a significant amount of work.

**Comment by mwakerman** [comment]
@dbarnett - take a look at PR #73 and let me know what you think. Pretty far reaching change. I'm sure there are some bugs around. Major changes and minor listed in the PR description.

https://5e5253eb7690da0008bb81fc--kanbanist.netlify.com/board

**Comment by dbarnett** [comment]
Cool! Far reaching change indeed, but I at least skimmed through to get the gist of the changes. Losing the link to the task in Todoist does seem unfortunate… is that no longer possible to support, or just missing in the short term until things settle more?

Is it possible to host both versions side-by-side for a while to get a feel for the differences?

**Comment by mwakerman** [comment]
Have brought back the link, I had just removed it because I thought it was clumsy and resulted in a lot of UI jitter when moving the mouse around. It's back now and a bit more subtle.

I don't think I'll try to host both versions just because of how broken the current one is for most users. Let me know if you find other regressions otherwise I plan on merging tomorrow night.

**Comment by mwakerman** [comment]
Latest: https://5e53b33e9672930008df8d63--kanbanist.netlify.com/

**Comment by dbarnett** [comment]
Oh, and just saw you had already posted a demo link. Looks nice, and plan sounds perfect to me. Thanks!

**Comment by mwakerman** [comment]
Done.
