### ISSUE TITLE
Thoughts on official Todoist kanban boards

### ISSUE THREAD

**Issue by dbarnett** [mwakerman/kanbanist#72]
Doist supposedly has their own kanban board support in the works
(mentioned in https://www.reddit.com/r/todoist/comments/f2sob0/im_amir_founder_and_ceo_at_doist_creators_of/fhffbdg). Do you expect to continue to maintain Kanbanist as an alternative?

**Comment by mwakerman** [comment]
@dbarnett - long term, probably not depending on whether they have all the features I/other people want. But generally I expect their product will be great and leave people little reason to keep using Kanbanist.

You might also have seen that Todoist's boards were originally slated for Q1 2019 (Doist's head of marketing comments on my [original Kanbanist video](https://www.youtube.com/watch?v=Y5rbyNZuFBQ)) and this tweet from Amir: [https://twitter.com/amix3k/status/1073162472876597249](https://twitter.com/amix3k/status/1073162472876597249) and then, as you linked, it's still "months away".

I'm in the middle of a pretty major refactor of things as discussed on #60 to fix the drag-and-drop issues (and complete incompatibility with Safari, sorry!). My goal is to have something done by the end of this week.

**Comment by dbarnett** [comment]
Yep, who knows when that will land.

Anyway, the Kanbanist view has breathed new life into my Todoist usage, so thank you for your work on it and I'm excited to hear the refactor is coming along. =)

**Comment by mwakerman** [comment]
Glad you've gotten some value from it and thanks for your contribution.
