### ISSUE TITLE
priority colors the same as in todoist

### ISSUE THREAD

**Issue by pdussart** [mwakerman/kanbanist#81]
I  think it would be easier to recognize priorities in Kanban.ist when the colors correspond with the the ones in Todoist: Red, Orange, Blue and White

**Comment by mwakerman** [comment]
@pdussart - thanks for the suggestion, this sounds reasonable. I've added the good-first-issue label and perhaps a contributor can pick this up.

**Comment by kantorge** [comment]
I've adjusted the colors in CSS, and created a pull request for it. Please let me know, if you have any comments, requests, or suggestions.
