### ISSUE TITLE
Drag and Drop Offset (Safari)

### ISSUE THREAD

**Issue by mwakerman** [mwakerman/kanbanist#9]
Halfway through 2018, dragging tasks and lists broke completely in Safari (Kanbanist currently doesn't work in Safari) and the drag offsets went crazy in Chrome and Firefox. I tried updating to the latest version of `react-dnd` but that did not solve the problem.

It appears to be related to a[long long standing issue](https://github.com/react-dnd/react-dnd/issues/552) with `react-dnd` but I'm unsure when Kanbanist became effected.

I think it calls for a different drag-and-drop library like [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd).

**Comment by Nornwen** [comment]
I am not sure if this is the same issue I am having, that happens when I drag and drop and the screen should scroll:

![image](https://user-images.githubusercontent.com/7502858/48552216-b7b5a380-e88c-11e8-948b-8b568d63659b.png)

**Comment by mwakerman** [comment]
Hi @Nornwen , I’m not certain either. I’ve got a branch in progress that is a pretty major refactor of the CSS structure and replacing react-dnd and I’m hopeful that it can fix a lot of these display issues. Thanks for reaching out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nornwen** [comment]
Is there any news on this? :)

**Comment by dbarnett** [comment]
@mwakerman Do you have any work in progress you can post for the CSS refactor, in case anyone else can pick up where you left off?

**Comment by mwakerman** [comment]
Resolved with re-write of drag-and-drop integration.
